[[redirects]]
  from = "/"
  to = "VITE_CLIENT_URI"
  status = 200
  force = true # COMMENT: ensure that we always redirect

[[redirects]]
  from = "/"
  to = "VITE_SERVER_URI"
  status = 200
  force = true # COMMENT: ensure that we always redirect